//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id { get; set; }
        public int PacienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoCitaId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual TipoCita TipoCita { get; set; }
    }
}
